using System.Globalization;
using System.Text;

namespace MiniTracker.Api.Backlog;

/// <summary>
/// Regenerates the STATUS-SUMMARY block in pure C# — no PowerShell, no external process. Rolls up by
/// status, by version (seeded from the roadmap), and by epic, and flags the highest-activity epic.
/// </summary>
public static class SummaryWriter
{
    public const string StartMarker =
        "<!-- STATUS-SUMMARY:START (generated by Mini Tracker - do not edit by hand) -->";
    public const string EndMarker = "<!-- STATUS-SUMMARY:END -->";

    private const string Dash = "—";  // em dash
    private const string Mid = "·";   // middle dot
    private const string Pin = "\U0001F4CD"; // round pushpin

    // Label -> emoji + activity rank (higher = more active). Order defines the "By status" listing order.
    private static readonly (string Label, string Emoji, int Rank)[] Statuses =
    {
        ("Not Yet Started", "⬜", 1),
        ("Under Review",    "\U0001F50D", 3),
        ("Refined",         "✨", 2),
        ("In Progress",     "\U0001F504", 5),
        ("Vendor Test",     "\U0001F9EA", 4),
        ("Done",            "✅", 0),
        ("On Hold",         "⏸", 0),
    };

    /// <summary>Builds the full START…END block (inclusive), using <paramref name="date"/> for the synced line.</summary>
    public static string Generate(Board board, DateOnly date)
    {
        var stories = board.Epics.SelectMany(e => e.Stories).ToList();

        var counts = Statuses.ToDictionary(s => s.Label, _ => 0);
        foreach (var s in stories)
            if (counts.ContainsKey(s.Status.Label)) counts[s.Status.Label]++;

        // Versions: seed every roadmap version (so V2 shows at 0), then count each story's version.
        var verCounts = new Dictionary<string, int>();
        foreach (var v in board.RoadmapVersions) verCounts.TryAdd(v, 0);
        foreach (var s in stories)
        {
            var ver = string.IsNullOrEmpty(s.Release) ? "Unscheduled" : s.Release;
            verCounts[ver] = verCounts.GetValueOrDefault(ver) + 1;
        }

        // Active epic = the one holding the highest-activity story; ties go to the earliest (file order).
        var rankOf = Statuses.ToDictionary(s => s.Label, s => s.Rank);
        int bestRank = -1; Epic? active = null;
        foreach (var e in board.Epics)
        {
            var er = 0;
            foreach (var s in e.Stories)
                if (rankOf.TryGetValue(s.Status.Label, out var r) && r > er) er = r;
            if (er > bestRank) { bestRank = er; active = e; }
        }

        var verKeys = verCounts.Keys.OrderBy(k =>
            k == "Unscheduled" ? double.MaxValue
            : double.Parse(k[1..], CultureInfo.InvariantCulture));

        var sb = new StringBuilder();
        sb.Append(StartMarker).Append('\n');
        sb.Append($"- [x] Synced {Dash} {stories.Count} stories {Dash} {date:yyyy-MM-dd}").Append('\n');
        sb.Append(active is not null && bestRank >= 1
            ? $"- {Pin} Current epic: **Epic {active.Number} {Dash} {active.Title}**"
            : $"- {Pin} Current epic: none active (all Done / On Hold)").Append('\n');
        sb.Append('\n');

        sb.Append("**By status**").Append('\n');
        foreach (var s in Statuses)
            sb.Append($"- {s.Emoji} {s.Label} {Dash} {counts[s.Label]}").Append('\n');
        sb.Append('\n');

        sb.Append("**By version**").Append('\n');
        foreach (var k in verKeys)
        {
            var label = k == "Unscheduled" ? "Unscheduled (trigger-based)" : k;
            sb.Append($"- {label} {Dash} {verCounts[k]}").Append('\n');
        }
        sb.Append('\n');

        sb.Append("**By epic**").Append('\n');
        foreach (var e in board.Epics)
        {
            var byStatus = Statuses.ToDictionary(s => s.Label, s => e.Stories.Count(st => st.Status.Label == s.Label));
            var parts = Statuses.Where(s => byStatus[s.Label] > 0).Select(s => $"{s.Emoji} {byStatus[s.Label]}");
            var joined = string.Join($" {Mid} ", parts);
            var suffix = joined.Length > 0 ? $" ({joined})" : "";
            var mark = active is not null && e.Number == active.Number && bestRank >= 1 ? $" {Pin}" : "";
            sb.Append($"- Epic {e.Number} {Dash} {e.Title} {Dash} {e.Stories.Count}{suffix}{mark}").Append('\n');
        }
        sb.Append(EndMarker);
        return sb.ToString();
    }
}
